version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./data
        target: /app/data
    environment:
      - GIN_MODE=release
    restart: unless-stopped